# Generated by Django 6.0.3 on 2026-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_register_created_at_remove_register_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('organizer', 'Organizer')], default='visitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
