# Generated by Django 6.0.3 on 2026-03-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_rename_first_name_register_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
