# Generated by Django 6.0.3 on 2026-03-15 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.country')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Art', 'Art & Culture'), ('Automobile', 'Automobile'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food & Beverage'), ('RealEstate', 'Real Estate'), ('Tourism', 'Tourism'), ('Sports', 'Sports')], max_length=100)),
                ('venue', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stall_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_stalls', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
