# Generated by Django 6.0.3 on 2026-03-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_contact_country_city_exhibition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='user',
            new_name='created_by',
        ),
    ]
