# Generated by Django 6.0.2 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_rename_user_exhibition_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Art', 'Art & Culture'), ('Automobile', 'Automobile'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food & Beverage'), ('RealEstate', 'Real Estate'), ('Tourism', 'Tourism'), ('Sports', 'Sports'), ('Industrial', 'Industrial')], max_length=100),
        ),
    ]
