# Generated by Django 6.0.3 on 2026-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_exhibition_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
