# Generated by Django 6.0.3 on 2026-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_rename_created_by_exhibition_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
