# Generated by Django 6.0.2 on 2026-03-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_booking_booking_type_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amenities', models.TextField(blank=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls_list', to='public.exhibition')),
            ],
            options={
                'unique_together': {('exhibition', 'stall_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='stall_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.stall'),
        ),
    ]
