# Generated by Django 6.0.2 on 2026-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_stall_booking_stall_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('big', 'Big (2X)'), ('vip', 'VIP (3X)')], default='normal', max_length=10),
        ),
    ]
