# Generated by Django 6.0.2 on 2026-03-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_stall_stall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('Visitor', 'Visitor'), ('Organizer', 'Organizer')], default='Visitor', max_length=20),
        ),
    ]
