# Generated by Django 6.0.2 on 2026-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_register_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
