# Generated by Django 6.0.2 on 2026-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_alter_register_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
