# Generated by Django 6.0.2 on 2026-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
