# Generated by Django 6.0.2 on 2026-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='dimensions',
            field=models.CharField(default='3m x 3m (9sqm)', max_length=50),
        ),
        migrations.AddField(
            model_name='stall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stalls/'),
        ),
        migrations.AddField(
            model_name='stall',
            name='position',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='stall',
            name='amenities',
            field=models.TextField(blank=True, default='High-speed WiFi (100Mbps), Dual 220V Power Outlets, 2 Chairs & 1 Information Desk, 3 Spotlight Fixtures'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('small', 'Small ($)'), ('large', 'Large ($$)')], default='small', max_length=10),
        ),
    ]
