# Generated by Django 6.0.2 on 2026-03-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_category_alter_exhibition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='category_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category'),
        ),
    ]
