# Generated by Django 6.0.2 on 2026-03-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0023_exhibition_category_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='category_link',
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category'),
        ),
    ]
