# Generated by Django 6.0.2 on 2026-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_remove_exhibition_category_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='stall',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
