# Generated by Django 6.0.2 on 2026-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='standard_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='vip_qty',
            field=models.IntegerField(default=0),
        ),
    ]
