# Generated by Django 6.0.2 on 2026-03-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0031_booking_business_category_booking_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_brochure_stand',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_extra_chairs',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_power_strip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_spotlight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_tv_display',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stall_description',
        ),
    ]
