# Generated by Django 6.0.2 on 2026-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0032_remove_booking_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_brochure_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_extra_chairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_power_strip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_tv_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='representative_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stall_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
