# Generated by Django 6.0.2 on 2026-03-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0033_booking_business_category_booking_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='business_category',
        ),
    ]
