# Generated by Django 6.0.2 on 2026-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0034_remove_booking_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
