# Generated by Django 6.0.2 on 2026-03-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0035_exhibition_end_time_exhibition_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
