# Generated by Django 6.0.3 on 2026-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0038_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
