# Generated by Django 6.0.3 on 2026-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_booking_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='student_ids/'),
        ),
    ]
