# Generated by Django 6.0.3 on 2026-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0040_booking_student_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('small', 'Small (₹)'), ('large', 'Large (₹₹)')], default='small', max_length=10),
        ),
    ]
