# Generated by Django 6.0.3 on 2026-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0042_contact_is_replied_contact_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role_upgrade_pending',
            field=models.BooleanField(default=False),
        ),
    ]
